expRef: "My fantastic experiment"
Organism: "NA"
inputFile: "/Users/splaisan/git_repos/Nucleomics-VIB/nanopore-tools/Nanopore_SumStatQC/RawData/data.bz2.bz2"
barcodeFile: "/Users/splaisan/git_repos/Nucleomics-VIB/nanopore-tools/Nanopore_SumStatQC/RawData/barcodes.bz2.bz2"
basecaller: "Guppy 2.0.10 - X5-GPU"
flowcellId: "FlowCell-ID"
flowcellType: "FLO-MIN106"
seqKit: "SQK-LSK108"
tutorialText: FALSE
sampleHours: 48
sampleIntervalMinutes: 60
