expRef: "My fantastic experiment"
Organism: "NA"
inputFile: "RawData/data.bz2"
barcodeFile: ""
basecaller: "Guppy 3.2.6 - X5 Mk1-GPU (hac)"
flowcellId: "<edit here>"
flowcellType: "FLO-MIN106/FLO-FLG001/FLGOP1"
seqKit: "SQK-RAD004/SQK-LSK109"
tutorialText: FALSE
sampleHours: 72
sampleIntervalMinutes: 60
# read length percentile limit, default to 0.975 to remove outliers
readlenpercentile: 1
